ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: ${PORT}
jwt:
  domain: "http://127.0.0.1:8082/"
  audience: "Fitness Audience"
  realm: "ktor sample app"
  issuer: "http://192.168.0.6:8082/"
  JWT_SECRET: ${secret}

mongoDB:
  CONNECTION_STRING: ${connectionString}
  DATABASE_NAME: "HealthDB"