ktor:
  application:
    modules:
      - com.example.ApplicationKt.module
  deployment:
    port: ${PORT}
jwt:
  domain: ${JWT_DOMAIN}
  audience: ${JWT_AUDIENCE}
  realm: "ktor sample app"
  issuer: "${JWT_ISSUER}
  JWT_SECRET: ${secret}

mongoDB:
  CONNECTION_STRING: ${MONGODB_URI}
  DATABASE_NAME: ${DATABASE_NAME}